[package]
name = "made"
description = "Made is a modern accessible development environment"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Julien Montagut <_@julienmontagut.com>"]
repository = "https://github.com/julienmontagut/made"
documentation = "https://github.com/julienmontagut/made#readme"
homepage = "https://github.com/julienmontagut/made"
keywords = ["editor", "terminal"]
categories = ["text-editors", "development-tools", "command-line-utilities"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.26"
toml = "0.8.19"
ratatui = "0.29.0"
crossterm = "0.28.1"
